
spring:
  data.mongodb:
    uri: ${MONGODB_URI}
    database: auction_db

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
