version: '3.5'

networks:
  kong-net:
    external: true

services:

  analiza:
    image: diegolirio/analisaleilao/analiza:0.0.1-SNAPSHOT
    container_name: analiza
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
      MONGODB_URI: mongodb://mongo:27017/auction_db
    networks:
      - kong-net

  mongo:
    image: mongo:4.4.26
    ports:
      - 27017:27017
    networks:
      - kong-net
