version: '3.5'

networks:
  kong-net:
    external: true

services:

  analiza:
    image: diegolirio/analisaleilao/analiza:0.0.1-SNAPSHOT
    container_name: analiza
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      MONGODB_URI:
      MAIL_USER:
      MAIL_PASS:
    networks:
      - kong-net
